import = ["/home/nawat/.config/alacritty/themes/themes/palenight.toml"]

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.9
